# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaVentas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(65, 126, 99, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 291, 41))
        self.label.setStyleSheet("color: rgb(85, 170, 127);\n"
"font: 87 16pt \"Arial Black\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 251, 41))
        self.label_2.setStyleSheet("color: rgb(85, 170, 127);\n"
"font: 87 12pt \"Arial Black\";")
        self.label_2.setObjectName("label_2")
        self.CampoIngresarCedula = QtWidgets.QLineEdit(self.centralwidget)
        self.CampoIngresarCedula.setGeometry(QtCore.QRect(290, 60, 181, 20))
        self.CampoIngresarCedula.setObjectName("CampoIngresarCedula")
        self.BotonInstanciarFactura = QtWidgets.QPushButton(self.centralwidget)
        self.BotonInstanciarFactura.setGeometry(QtCore.QRect(500, 60, 131, 23))
        self.BotonInstanciarFactura.setObjectName("BotonInstanciarFactura")
        self.frameAgregarProductos = QtWidgets.QFrame(self.centralwidget)
        self.frameAgregarProductos.setEnabled(False)
        self.frameAgregarProductos.setGeometry(QtCore.QRect(20, 100, 761, 441))
        self.frameAgregarProductos.setStyleSheet("QWidget#frame{\n"
"background-color: qlineargradient(spread:repeat, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(65, 126, 99, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.frameAgregarProductos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAgregarProductos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameAgregarProductos.setObjectName("frameAgregarProductos")
        self.comboBoxListaStock = QtWidgets.QComboBox(self.frameAgregarProductos)
        self.comboBoxListaStock.setGeometry(QtCore.QRect(280, 20, 221, 22))
        self.comboBoxListaStock.setStyleSheet("")
        self.comboBoxListaStock.setObjectName("comboBoxListaStock")
        self.label_3 = QtWidgets.QLabel(self.frameAgregarProductos)
        self.label_3.setGeometry(QtCore.QRect(30, 10, 251, 41))
        self.label_3.setStyleSheet("color: rgb(85, 170, 127);\n"
"font: 87 8pt \"Arial Black\";")
        self.label_3.setObjectName("label_3")
        self.BotonAsociarProductoFactura = QtWidgets.QPushButton(self.frameAgregarProductos)
        self.BotonAsociarProductoFactura.setGeometry(QtCore.QRect(540, 20, 131, 23))
        self.BotonAsociarProductoFactura.setObjectName("BotonAsociarProductoFactura")
        self.BotonAsociar = QtWidgets.QPushButton(self.frameAgregarProductos)
        self.BotonAsociar.setGeometry(QtCore.QRect(300, 90, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BotonAsociar.setFont(font)
        self.BotonAsociar.setStyleSheet("font: 14pt \"Papyrus\";\n"
"")
        self.BotonAsociar.setObjectName("BotonAsociar")
        self.BotonVolverMenuPrincipal = QtWidgets.QPushButton(self.centralwidget)
        self.BotonVolverMenuPrincipal.setGeometry(QtCore.QRect(20, 10, 171, 23))
        self.BotonVolverMenuPrincipal.setObjectName("BotonVolverMenuPrincipal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VENTAS Y FACTURACIÓN"))
        self.label_2.setText(_translate("MainWindow", "Cedula del cliente a facturar"))
        self.BotonInstanciarFactura.setText(_translate("MainWindow", "EMPEZAR A FACTURAR"))
        self.label_3.setText(_translate("MainWindow", "Elegir producto para agregar a la factura"))
        self.BotonAsociarProductoFactura.setText(_translate("MainWindow", "AGREGAR PRODUCTO"))
        self.BotonAsociar.setText(_translate("MainWindow", "FACTURAR"))
        self.BotonVolverMenuPrincipal.setText(_translate("MainWindow", "VOLVER AL MENÚ PRINCIPAL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
